name: GSC Full Fetch → CSV Artifact

on:
  workflow_dispatch:
  schedule:
#    - cron: "30 22 * * *"  # 2:00 AM Tehran time

jobs:
  gsc-fullfetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas pyarrow google-cloud-bigquery tqdm db-dtypes pandas_gbq

      - name: Write GCP credentials file
        run: |
          if [ -n "${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY_BASE64 }}" ]; then
            printf "%s" "${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY_BASE64 }}" | base64 --decode > gcp-key.json
            echo "✅ WROTE: gcp-key.json from BAMTABRIDSAZAN_GCP_SA_KEY_BASE64"
          elif [ -n "${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY }}" ]; then
            printf "%s" "${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY }}" > gcp-key.json
            echo "✅ WROTE: gcp-key.json from BAMTABRIDSAZAN_GCP_SA_KEY (raw)"
          else
            echo "❌ ERROR: Missing GCP credentials secret."
            exit 1
          fi
          echo "gcp-key.json size:" $(wc -c < gcp-key.json)

      - name: Validate gcp-key.json
        run: python -c "import json; json.load(open('gcp-key.json')); print('✅ gcp-key.json is valid')"

      - name: Run GSC → Full Fetch CSV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
        run: |
          echo "🚀 Running GSC Full Fetch..."
          python gsc_to_bq_fullfetch_test.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsc_fullfetch_csv
          path: gsc_fullfetch_test_*.csv
