name: Run GSC Debug Batches

on:
  workflow_dispatch:  # اجرا دستی

jobs:
  run-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # نصب dependencies اصلی
          if [ -f bamtabridsazan_gsc-to-bq/requirements.txt ]; then pip install -r bamtabridsazan_gsc-to-bq/requirements.txt; fi
          # اطمینان از نصب کتابخانه های گوگل
          pip install pandas google-auth google-cloud-bigquery google-api-python-client google-auth-httplib2
          # رفع ارورهای انتهای فایل output
          pip install db-dtypes pyarrow

      # ✅ ساخت فایل gcp-key.json از سکرت Base64
      - name: Decode GCP Key from Base64
        run: |
          echo "$BAMTABRIDSAZAN_GCP_SA_KEY_BASE64" | base64 --decode > gcp-key.json
        env:
          BAMTABRIDSAZAN_GCP_SA_KEY_BASE64: ${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY_BASE64 }}

      - name: Run debug Python script
        run: |
          echo "Running script: ./gsc-to-bq-debug-batches.py"
          python ./gsc-to-bq-debug-batches.py > output_debug.txt || echo "Script failed with exit code $?"

      # ✅ آپلود artifact های دیباگ
      - name: Upload debug output TXT
        uses: actions/upload-artifact@v4
        with:
          name: gsc-debug-output-txt
          path: output_debug.txt

      - name: Upload debug CSV with unique_key_new
        uses: actions/upload-artifact@v4
        with:
          name: gsc-debug-output-csv
          path: output_debug.csv

      - name: Upload duplicates report
        uses: actions/upload-artifact@v4
        with:
          name: gsc-debug-duplicates
          path: duplicates_report.csv
