name: Run GSC Debug Batches

on:
  workflow_dispatch:  # اجازه اجرا دستی ورک‌فلو

jobs:
  run-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f bamtabridsazan_gsc-to-bq/requirements.txt ]; then pip install -r bamtabridsazan_gsc-to-bq/requirements.txt; fi

      - name: List repo files for debug
        run: |
          echo "Listing repo files to check paths..."
          ls -R

      - name: Run debug Python script
        run: |
          cd bamtabridsazan_gsc-to-bq
          python gsc-to-bq-debug-batches.py > ../output_debug.txt


      - name: Upload debug output
        uses: actions/upload-artifact@v4
        with:
          name: gsc-debug-output
          path: output_debug.txt
