name: GSC Full Fetch to BigQuery

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date YYYY-MM-DD'
        required: true
        default: '2024-01-01'
      end_date:
        description: 'End date YYYY-MM-DD'
        required: true
        default: '2025-10-01'
      debug:
        description: 'Debug mode (true/false)'
        required: false
        default: 'false'
      csv_test:
        description: 'Path to CSV test file (optional)'
        required: false

jobs:
  full_fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GSC Full Fetch
        env:
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}
          DEBUG_FLAG: ${{ github.event.inputs.debug }}
          CSV_TEST: ${{ github.event.inputs.csv_test }}
        run: |
          CMD="python gsc_to_bq_rev5_fullfetch.py --start-date $START_DATE --end-date $END_DATE"
          if [ "$DEBUG_FLAG" = "true" ]; then
            CMD="$CMD --debug"
          fi
          if [ -n "$CSV_TEST" ]; then
            CMD="$CMD --csv-test $CSV_TEST"
          fi
          echo "Running command: $CMD"
          $CMD

      - name: Confirm BigQuery table
        run: |
          echo "Check your BQ dataset: bamtabridsazan.seo_reports.bamtabridsazan__gsc__raw_data_fullfetch"
