name: GSC to BigQuery (Full Fetch)

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date YYYY-MM-DD'
        required: true
      end_date:
        description: 'End date YYYY-MM-DD'
        required: true
      debug:
        description: 'Enable debug mode (true/false)'
        required: false
        default: 'false'

jobs:
  fullfetch-gsc-to-bq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client google-cloud-bigquery tqdm pandas pyarrow db-dtypes pandas_gbq

      - name: Write GCP credentials file
        run: |
          if [ -n "${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY_BASE64 }}" ]; then
            printf "%s" "${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY_BASE64 }}" | base64 --decode > gcp-key.json
          elif [ -n "${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY }}" ]; then
            printf "%s" "${{ secrets.BAMTABRIDSAZAN_GCP_SA_KEY }}" > gcp-key.json
          else
            echo "❌ ERROR: Missing GCP credentials secret."
            exit 1
          fi
          echo "gcp-key.json size:" $(wc -c < gcp-key.json)

      - name: Validate gcp-key.json
        run: python -c "import json; json.load(open('gcp-key.json')); print('✅ gcp-key.json is valid')"

      - name: Run Full Fetch Python
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
        run: |
          DEBUG_FLAG=$([[ "${{ github.event.inputs.debug }}" == "true" ]] && echo "--debug")
          CSV_TEST_FILE="gsc_fullfetch_test_${{ github.run_id }}.csv"

          python gsc_to_bq_rev5_fullfetch.py \
            ${DEBUG_FLAG} \
            --start-date "${{ github.event.inputs.start_date }}" \
            --end-date "${{ github.event.inputs.end_date }}" \
            --csv-test "${CSV_TEST_FILE}"
