name: GSC Full Fetch to BigQuery

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: true
      debug:
        description: 'Enable debug mode (true/false)'
        required: false
        default: 'false'
      csv_test:
        description: 'Optional CSV file path for testing'
        required: false
        default: ''

jobs:
  fullfetch:
    runs-on: ubuntu-latest
    env:
      GCP_KEY_PATH: ${{ secrets.GCP_KEY_JSON_PATH }}  # مسیر سرویس اکانت در رنر

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-cloud-bigquery

      - name: Run GSC Full Fetch
        run: |
          START_DATE="${{ github.event.inputs.start_date }}"
          END_DATE="${{ github.event.inputs.end_date }}"
          DEBUG_FLAG=$([[ "${{ github.event.inputs.debug }}" == "true" ]] && echo "--debug")
          CSV_FLAG=""
          if [[ ! -z "${{ github.event.inputs.csv_test }}" ]]; then
            CSV_FLAG="--csv-test ${{ github.event.inputs.csv_test }}"
          fi
          echo "[INFO] Running GSC Full Fetch: $START_DATE -> $END_DATE"
          python gsc_to_bq_rev5_fullfetch.py --start-date $START_DATE --end-date $END_DATE $DEBUG_FLAG $CSV_FLAG

      - name: Upload CSV artifact (optional)
        if: ${{ github.event.inputs.csv_test != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: gsc_csv_test
          path: ${{ github.event.inputs.csv_test }}
